name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
variables:
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  # These will need to be changed  for your project.
  CI_BUILD_URL: "https://dev.azure.com/sunpy/ndcube/_build/results?buildId=$(Build.BuildId)"
  CIBW_BUILD: cp36-* cp37-*
  CIBW_SKIP: "*-win32 *-manylinux1_i686"

# These resources need to be setup on the Azure Pipeline website
# as a service connection (if it has not been already).
resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: sunpy
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - 'v*'
    exclude:
    - '*dev*'
    - '*pre*'
    - '*post*'

jobs:
- template: run-tox-env.yml@OpenAstronomy
  parameters:
    submodules: false
    coverage: codecov
    envs:
      - linux: pycodestyle

      - macos: py37-offline
        name: py37_offline

      - windows: py36-offline
        name: py36_offline

      - linux: py37-online
        name: py37_online

      - linux: py37-astropydev

      - linux: py37-sunpydev


# On branches which aren't master, and not Pull Requests, build the wheels but only upload them on tags
- ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), not(contains(variables['Build.SourceBranch'], 'master'))) }}:
  - template: publish.yml@OpenAstronomy
    parameters:
      # Only Upload to PyPI on tags
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
        pypi_connection_name : 'PyPI'
      test_extras: 'dev'
      test_command: 'pytest -p no:warnings --doctest-rst -m "not figure" --pyargs ndcube'
      submodules: false
      targets:
        - sdist
      dependsOn:
        - py37_offline
        - py36_offline
        - py37_online
